name: Create Beta Build

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (packages)
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip gnu-sed

      - name: Select Xcode 15.1
        run: | 
          sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer
          mkdir upload

      - name: Compile f
        run: | 
          make package SCHEME="'feather (Release)'"
          mv packages/* upload/

      - name: Get Version Number
        id: get_version
        run: |
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Payload/feather.app/Info.plist)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV








      - name: Send Discord build message
        run: |
          COMMIT_HASH=$(git log -1 --pretty=format:'%h') &&
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s') &&
          (
          curl "${{ secrets.B_WEBHOOK }}" -sS -H "Content-Type:application/json" -X POST -d '{
            "content":null,
            "embeds":[
              {
                "title":"${{ github.repository }} [Build ${{ github.run_number }}]",
                "description":"[`'"$COMMIT_HASH"'`](https://github.com/${{ github.repository }}/commit/'"$COMMIT_HASH"') '"$COMMIT_MESSAGE"'",
                "url":"https://github.com/${{ github.repository }}/actions/runs/${GITHUB_RUN_ID}",
                "color":6648790,
                "author":{
                  "name":"${{ github.actor }}",
                  "icon_url":"https://github.com/${{ github.actor }}.png"
                }
              }
            ],
            "attachments":[],
            "components":[
              {
                "type":1,
                "components":[
                  {
                    "type":2,
                    "url":"https://google.com",
                    "label":"Download",
                    "style":5
                  }
                ]
              }
            ]
          }')
          )
